MineralCatalogue/mineral_catalogue/mineral_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('rocks.urls', namespace="rocks")),
    # https://www.youtube.com/watch?v=iSVDQ-TAex4
    path(r'^__debug__', include(debug_toolbar.urls))
]

MineralCatalogue/mineral_catalogue/rocks/urls.py
from . import views
from django.urls import path

app_name = "rocks"

urlpatterns = [

    path('home/<str:letter>/', views.index_view, name="index"),
    path('mineral/<int:pk>/', views.details_view, name="details"),
    path('home/random/random/', views.random_view, name="random"),


]

MineralCatalogue/mineral_catalogue/rocks/models.py
from django.db import models

# Create your models here.

class Mineral(models.Model):
    '''
        THE MINERAL MODEL TAKES IN CHARACTERS, BUT IF THE FIELD IS LEFT EMPTY,
        BLANK=TRUE ALLOWS IT TO BE EMPTY.
    '''

    name = models.CharField(max_length=128, blank=True)
    image_filename = models.CharField(max_length=255, blank=True)
    image_caption = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=128, blank=True)
    formula = models.CharField(max_length=255, blank=True)
    strunz_classification = models.CharField(max_length=255, blank=True)
    color = models.CharField(max_length=255, blank=True)
    crystal_system = models.CharField(max_length=255, blank=True)
    unit_cell = models.CharField(max_length=255, blank=True)
    crystal_symmetry = models.CharField(max_length=255, blank=True)
    cleavage = models.CharField(max_length=255, blank=True)
    mohs_scale_hardness = models.CharField(max_length=255, blank=True)
    luster = models.CharField(max_length=255, blank=True)
    streak = models.CharField(max_length=255, blank=True)
    diaphaneity = models.CharField(max_length=255, blank=True)
    optical_properties = models.CharField(max_length=255, blank=True)
    refractive_index = models.CharField(max_length=255, blank=True)
    crystal_habit = models.CharField(max_length=255, blank=True)
    specific_gravity = models.CharField(max_length=255, blank=True)

MineralCatalogue/mineral_catalogue/rocks/forms.py
from django import forms




class Search_Form(forms.Form):
    name = forms.CharField(max_length=100)

MineralCatalogue/mineral_catalogue/rocks/views.py
'''
   BELOW ARE MY VIEWS. THREE OF THEM WILL COLLECT INFORMATION,
   THEN FEED IT TO THE TEMPLATE.
'''

from django.shortcuts import render, get_object_or_404, reverse
from .models import Mineral
from random import choice
from django.http import HttpResponseRedirect



def index_view(request, letter):
    if request.method == 'POST':
        name = request.POST.get('name')
        # This if statement looks for the search bar inputs
        mins = Mineral.objects.filter(name__icontains=name)

    # This elif finds all objects when a user clicks on home
    elif letter == 'home':
        mins = Mineral.objects.all()

    # All other elifs search by category, the category navbar
    elif letter == 'silicate':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'oxide':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'sulfate':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'sulfide':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'carbonate':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'halide':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'sulfosalt':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'phosphate':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'borate':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'organic':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'arsenate':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'native elements':
        mins = Mineral.objects.filter(category__icontains=letter)

    elif letter == 'other':
        mins = Mineral.objects.filter(category__icontains=letter)

    else:
        # This else looks for objects in the letter navbar
        mins = Mineral.objects.filter(name__startswith=letter)


    minerals = {'mineral_names':mins}

    return render(request, 'rocks/index.html', context=minerals)




def details_view(request, pk):
    '''
        DETAILS VIEW WORKS OFF OF THE INDEX VIEW. WHEN SOMEONE CHOOSES A MINERAL
        FROM THE INDEX URL PAGE, THE PK OF THE MINERAL IS CAPTURED AND GIVEN TO
        DETAILS VIEW. THE DETAILS VIEW THEN LOOKS THROUGH THE DATABASE FOR THE
        MATCHING MINERAL USING THE PK, THEN RENDERS IT.
    '''


    mins = get_object_or_404(Mineral, pk=pk)
    minerals = {"mineral_detail": mins}


    return render(request, "rocks/details.html", context=minerals)

def random_view(request):
    '''
       RANDOM VIEW SELECTS ALL OF THE OBJECTS FROM THE DATABASE, THEN THE
       CHOICE FUNCTION PICS OUT ONE ENTRY RANDOMLY, THEN RENDERS THE IT TO THE
       TEMPLATE
    '''

    all = Mineral.objects.all()

    new_all = choice(all)
    random = {"random_mineral": new_all}

    return render(request, "rocks/random.html", context=random)

MineralCatalogue/mineral_catalogue/rocks/templates/rocks/details.html
{% extends "layout.html" %}
{% load staticfiles %}

<h1>hello</h1>
{% block content %}


        <div class="grid-100 mineral__container">
            <h1 class="mineral__name">{{ mineral_detail.name|title }}</h1>
            <div class="mineral__image-bg">
                <!--<img src="/static/images/{{ mineral_detail.image_filename }}" alt="">-->
                <!-- Notice the difference between the above img tag and the below. IF someone was to take your rocks app
                And they used it in their django project, the file path of the img tag above could be wrong.
                How to combat this? By using the static_url below. So if you changed the folder from static to asset, or to anything else,
                you would have to go through all of your code and change all the /static/ to /asset/,
                its a way to hide the folder structure, or mask it in the URL.-->
                <img class="mineral__image" src="{{ STATIC_URL }}/images/{{ mineral_detail.image_filename }}" alt="">

                 <p class="mineral__caption">{{ mineral_detail.image_caption }}</p>
            </div>
            <div class="mineral__table-container">
                <table class="mineral__table" style="color: rosybrown">
                    <tr>
                        <td class="mineral__category">Category</td>
                        <td>{{ mineral_detail.category|title }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Formula</td>
                        <td>{{ mineral_detail.formula|title }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Strunz Classification</td>
                        <td>{{ mineral_detail.strunz_classification|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Color</td>
                        <td>{{ mineral_detail.color|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal System</td>
                        <td>{{ mineral_detail.crystal_system|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Unit Cell</td>
                        <td>{{ mineral_detail.unit_cell|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal Symmetry</td>
                        <td>{{ mineral_detail.crystal_symmetry|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Cleavage</td>
                        <td>{{ mineral_detail.cleavage|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Mohs Scale Hardness</td>
                        <td>{{ mineral_detail.mohs_scale_hardness|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Luster</td>
                        <td>{{ mineral_detail.Luster|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Streak</td>
                        <td>{{ mineral_detail.streak|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Diaphaneity</td>
                        <td>{{ mineral_detail.diaphaneity|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Optical Properties</td>
                        <td>{{ mineral_detail.optical_properties|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Refractive Index</td>
                        <td>{{ mineral_detail.refractive_index|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal Habit</td>
                        <td>{{ mineral_detail.crystal_habit|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Specific Gravity</td>
                        <td>{{ mineral_detail.specific_gravity|title  }}</td>
                    </tr>


                </table>

            </div>

        </div>



{% endblock %}

MineralCatalogue/mineral_catalogue/rocks/templates/rocks/index.html
{% extends 'layout.html' %}
{% load staticfiles %}


{% block content %}

        <div class="grid-100">

            <ul class="minerals__container ">
                {% for mineral in mineral_names %}
                    <li class="minerals__item">
                        <a class = "minerals__anchor" href="{% url "rocks:details" pk=mineral.id %}">{{ mineral.name }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>

{% endblock %}

MineralCatalogue/mineral_catalogue/rocks/templates/rocks/random.html
{% extends "layout.html" %}
{% load staticfiles %}


{% block content %}


        <div class="grid-100 mineral__container">
            <h1 class="mineral__name">{{ random_mineral.name|title }}</h1>
            <div class="mineral__image-bg">
                <!--<img src="/static/images/{{ random_mineral.image_filename }}" alt="">-->
                <!-- Notice the difference between the above img tag and the below. IF someone was to take your rocks app
                And they used it in their django project, the file path of the img tag above could be wrong.
                How to combat this? By using the static_url below. So if you changed the folder from static to asset, or to anything else,
                you would have to go through all of your code and change all the /static/ to /asset/,
                its a way to hide the folder structure, or mask it in the URL.-->
                <img class="mineral__image" src="{{ STATIC_URL }}/images/{{ random_mineral.image_filename }}" alt="">

                 <p class="mineral__caption">{{ random_mineral.image_caption }}</p>
            </div>
            <div class="mineral__table-container">
                <table class="mineral__table" style="color: rosybrown">
                    <tr>
                        <td class="mineral__category">Category</td>
                        <td>{{ random_mineral.category|title }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Formula</td>
                        <td>{{ random_mineral.formula|title }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Strunz Classification</td>
                        <td>{{ random_mineral.strunz_classification|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Color</td>
                        <td>{{ random_mineral.color|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal System</td>
                        <td>{{ random_mineral.crystal_system|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Unit Cell</td>
                        <td>{{ random_mineral.unit_cell|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal Symmetry</td>
                        <td>{{ random_mineral.crystal_symmetry|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Cleavage</td>
                        <td>{{ random_mineral.cleavage|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Mohs Scale Hardness</td>
                        <td>{{ random_mineral.mohs_scale_hardness|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Luster</td>
                        <td>{{ random_mineral.Luster|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Streak</td>
                        <td>{{ random_mineral.streak|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Diaphaneity</td>
                        <td>{{ random_mineral.diaphaneity|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Optical Properties</td>
                        <td>{{ random_mineral.optical_properties|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Refractive Index</td>
                        <td>{{ random_mineral.refractive_index|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Crystal Habit</td>
                        <td>{{ random_mineral.crystal_habit|title  }}</td>
                    </tr>
                    <tr>
                        <td class="mineral__category">Specific Gravity</td>
                        <td>{{ random_mineral.specific_gravity|title  }}</td>
                    </tr>


                </table>

            </div>

        </div>



{% endblock %}

MineralCatalogue/mineral_catalogue/templates/layout.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <style>
        a:hover {
        background-color: yellow;
                }
    </style>
    <meta charset="UTF-8">
    <title>All About Minerals!</title>
    <link rel="stylesheet" href="{% static 'css/global.css'  %}">
</head>




<body>

<div>
            <nav>
                <li>a</li>

                <li>b</li>
                <li>c</li>
            </nav>

</div>


<div class ="box1"> 1</div>
<div class ="box1"> 2</div>

    <div class="bounds">

        <div class="">
            <nav class="nav">
                <ul>

                    <li>
                        <a class="" href="{% url "rocks:index" letter='home' %}">Home</a>
                    </li>

                    <li class="">
                        <a href="{% url 'rocks:index' letter='A' %}">A</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='B' %}">B</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='C' %}">C</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='D' %}">D</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='E' %}">E</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='F' %}">F</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='G' %}">G</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='H' %}">H</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='I' %}">I</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='J' %}">J</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='K' %}">K</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='L' %}">L</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='M' %}">M</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='N' %}">N</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='O' %}">O</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='P' %}">P</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='Q' %}">Q</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='R' %}">R</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='S' %}">S</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='T' %}">T</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='U' %}">U</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='V' %}">V</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='W' %}">W</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='X' %}">X</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='Y' %}">Y</a>
                    </li>
                    <li>
                        <a href="{% url 'rocks:index' letter='Z' %}">Z</a>
                    </li>
                    <div>

                        <form action="" method="POST" >
                            {% csrf_token %}
                            <input type="search" placeholder="Search For Mineral" name="name">
                            <input type="submit" value="Submit">
                        </form>

                    </div>
                </ul>
            </nav>
        </div>

        <div>
            <nav class="nav">
                <ul>
                    <li><a href="{% url 'rocks:index' letter='silicate' %}">Silicates</a></li>
                    <li><a href="{% url 'rocks:index' letter='oxide' %}">Oxides</a></li>
                    <li><a href="{% url 'rocks:index' letter='sulfate' %}">Sulphates</a></li>
                    <li><a href="{% url 'rocks:index' letter='sulfide' %}">Sulphides</a></li>
                    <li><a href="{% url 'rocks:index' letter='carbonate' %}">Carbonates</a></li>
                    <li><a href="{% url 'rocks:index' letter='halide' %}">Halides</a></li>
                    <li><a href="{% url 'rocks:index' letter='sulfosalt' %}">Sulfosalts</a></li>
                    <li><a href="{% url 'rocks:index' letter='phosphate' %}">Phosphates</a></li>
                    <li><a href="{% url 'rocks:index' letter='borate' %}">Borates</a></li>
                    <li><a href="{% url 'rocks:index' letter='organic' %}">Organic Mineral</a></li>
                    <li><a href="{% url 'rocks:index' letter='arsenate' %}">Arsenates</a></li>
                    <li><a href="{% url 'rocks:index' letter='native elements' %}">Native Elements</a></li>
                    <li><a href="{% url 'rocks:index' letter='other' %}">Other</a></li>
                </ul>
            </nav>


        </div>


        <div class="grid-100">

            <div class="mineral__container">
                <img class="mineral__image rotate thumbnail"  src="{% static "/images/Therock.jpg" %}" alt="">
                <h1 style="color: rosybrown;">Rocks!</h1>
                <h3 style="color: #999999">..or are they Minerals?</h3>

            </div>

            {% block content %}{% endblock %}
        </div>



    </div>

    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url "rocks:random" %}">Generate Random Mineral!!!</a>
    </div>
</body>
</html>